apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-disconnected-policy-clusterversion-upstream
  namespace: default
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.IP Information Protection Processes and Procedures
    policy.mcm.ibm.com/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: ClusterVersion
        metadata:
          name: version
        spec:
          # channel: stable-4.3
          # clusterID: 70d93278-a909-4f87-b388-4566ba7814b1
          #upstream: https://api.openshift.com/api/upgrades_info/v1/graph2
          upstream: https://example-cincinnati-policy-engine-route-openshift-cincinnati.apps.rwsu-managed.devcluster.openshift.com/api/upgrades_info/v1/graph2
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: openshift-disconnected-binding-clusterversion-upstream
  namespace: default
placementRef:
  name: openshift-disconnected-placement-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: openshift-disconnected-policy-clusterversion-upstream
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-disconnected-placement-rule
  namespace: default
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchLabels:
      vendor: OpenShift


